### ISSUE TITLE
unexpected token '='. expected an opening '(' before a method's parameter list

### ISSUE THREAD

**Issue by OliverNi** [callstack/nativepack#27]
## Environment

@callstack/nativepack: "1.4.0"
Android 11.0 emulator
Clean app created with:
npx react-native init MyApp --template react-native-template-typescript

## Description
With the default template an error is thrown when the app launches in my android simulator. 
"unexpected token '='. expected an opening '(' before a method's parameter list".
The error is actually caused by the nativepack package not being transpiled and it can be solved by letting the babel-loader transpile it.
```javascript
module: {
  rules: [
  {
    test: /\.[jt]sx?$/,
    include: [
      /node_modules(.*[/\\])+react/,
      /node_modules(.*[/\\])+@react-native/,
      /node_modules(.*[/\\])+@react-navigation/,
      /node_modules(.*[/\\])+@react-native-community/,
      /node_modules(.*[/\\])+@expo/,
      /node_modules(.*[/\\])+pretty-format/,
      /node_modules(.*[/\\])+metro/,
      /node_modules(.*[/\\])+abort-controller/,
      /node_modules(.*[/\\])+@callstack\/nativepack/,
    ],
    use: 'babel-loader',
  },
}
```

Seeing as nativepack will always need to be transpiled, unless I'm missing something, maybe this should be included in the default template?

I'm new to RN so I could be wrong.

## Reproducible Demo
Follow steps in README.
https://github.com/OliverNi/react-native-app-nativepack

**Comment by zamotany** [comment]
I need to dig deeper into this. The TesterApp which is RN 0.64 was working correctly on both iOS and Android. Additionally all source files from `@callstack/nativepack` are transpiled.

**Comment by zamotany** [comment]
@OliverNi Do you know which file is causing the `unexpected token` error?

**Comment by OliverNi** [comment]
> @OliverNi Do you know which file is causing the `unexpected token` error?

No, unfortunately not. There is not much information about the error so I basically had to guess my way to which dependency that caused it.

**Comment by zamotany** [comment]
@OliverNi I've created a PR with the fix which essentially add that additional regex to the `include` array.
