### ISSUE TITLE
Unable to compile Android

### ISSUE THREAD

**Issue by jaridmargolin** [callstack/nativepack#28]
## Description

Android app does not compile. I believe it is due to the recent rename to nativepack.

## Reproducible Demo

I have not verified, but my assumption is that this should fail for all Android compilations since nativepack v1.4.0.

## Additional Notes

It looks like there were a few places where the package was not updated:
* https://github.com/callstack/nativepack/blob/main/android/src/main/java/com/callstack/nativepack/ChunkLoader.kt#L1
* https://github.com/callstack/nativepack/blob/main/android/src/main/java/com/callstack/nativepack/ChunkLoadingError.kt
* https://github.com/callstack/nativepack/blob/main/android/src/main/java/com/callstack/nativepack/FileSystemChunkLoader.kt
* https://github.com/callstack/nativepack/blob/main/android/src/main/java/com/callstack/nativepack/RemoteChunkLoader.kt
* https://github.com/callstack/nativepack/blob/main/android/src/main/java/com/callstack/nativepack/WebpackToolkitModule.kt
* https://github.com/callstack/nativepack/blob/main/android/src/main/java/com/callstack/nativepack/WebpackToolkitPackage.kt

I manually modified these files within my node_modules dir to use `package com.callstack.nativepack` and everything appears to be compiling now.

**Comment by OliverNi** [comment]
I have an open pull request for this fix.
https://github.com/callstack/nativepack/pull/26

**Comment by zamotany** [comment]
Yup, you're right. I have merged the PR and will do a release soon.

**Comment by jaridmargolin** [comment]
Thank @OliverNi and @zamotany. Will be awaiting the release 😊.

**Comment by zamotany** [comment]
@jaridmargolin  @OliverNi Version `1.4.1` just got released. I'm going to close this issue for now. Should there be any problems, feel free to reopen it.
