### ISSUE TITLE
HMR has some Error!

### ISSUE THREAD

**Issue by NiuGuohui** [callstack/nativepack#29]
## Environment

- Android
- Use TypeScript

## Description

![image](https://user-images.githubusercontent.com/37471959/118474254-73493e00-b73d-11eb-8c01-bb9b80e87f7b.png)

When I changed ```App.tsx```,the HMR report an error.

## Reproducible Demo
RN official demo:

index.js
```
import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';

AppRegistry.registerComponent(appName, () => App);
```

**Comment by zamotany** [comment]
Can you post which React Native version you're using?

**Comment by NiuGuohui** [comment]
> Can you post which React Native version you're using?

0.64.0

**Comment by OliverNi** [comment]
I had the same issue before when hermes was disabled.
Try setting enableHermes to true in android/app/build.gradle.

Here's what mine looks like:
```
project.ext.react = [
    enableHermes: true,
    bundleCommand: "webpack-bundle",
    bundleInDebug: false
]
```

**Comment by zamotany** [comment]
Can someone create a repro project where this issue can be seen? In TesterApp the HMR works both with and without Hermes on Android.

**Comment by OliverNi** [comment]
https://github.com/OliverNi/react-native-app-nativepack
This can be used to reproduce the issue.
The TesterApp in the nativepack repo works for me as well. I also tried to extract to TesterApp to a separate project and changed nativepack to an external dependency and the issue was reproducible in that project as well. 

It fails when evaluating the script in loadHmrUpdate so it's pretty difficult to debug.
```javascript
      if (globalEvalWithSourceUrl) {
        globalEvalWithSourceUrl(script, null);
      } else {
        // Fails here
        eval(script);
      }
```

**Comment by NiuGuohui** [comment]
[https://github.com/NiuGuohui/nativepack-issue-29](https://github.com/NiuGuohui/nativepack-issue-29)
This repo can be seen this issue.

**Comment by zamotany** [comment]
I think I got the fix for it. @OliverNi @NiuGuohui can you update `@callstack/nativepack` to `1.4.2-beta.0` and check if the issue is gone? Also when testing keep in mind this limitation: https://github.com/callstack/nativepack#hot-module-replacement--react-refresh

**Comment by NiuGuohui** [comment]
> I think I got the fix for it. @OliverNi @NiuGuohui can you update `@callstack/nativepack` to `1.4.2-beta.0` and check if the issue is gone? Also when testing keep in mind this limitation: https://github.com/callstack/nativepack#hot-module-replacement--react-refresh

Thank you, the issue has been eliminated.:smile:
